import type { NextPage } from "next";
import Head from "next/head";
import { styled, Heading, Box } from "@cabindao/topo";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading>Test</Heading>
      </main>
    </Box>
  );
};

export default Home;
