import type { NextPage } from "next";
import Head from "next/head";
import { styled, Heading, Box } from "@cabindao/topo";
import { getBillboards } from "@api/billboards";
import BillboardCard from "@components/BillboardCard"

export async function getServerSideProps(context) {
  const records = await getBillboards();

  return {
    props: {
      records,
    },
  };
}

const Home: NextPage = ({ records }) => {
  console.log(records);

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading>Test</Heading>
        <ul>
          {records.map(record => (
            <BillboardCard {...record} key={record.Name}/>
          ))}
        </ul>
      </main>
    </Box>
  );
};

export default Home;
